server.port=8081
spring.application.name=D55P1-1

# MySQL settings
spring.datasource.url=jdbc:mysql://localhost:3306/prodapt2
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka settings
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true